$(document).ready(function(){
    $('.food-slider').slick({
        autoplay:true,
       slidesToShow:3,
       slideToScroll:1,
       prevArrow:".prev-btn",
       nextArrow:".next-btn",
       responsive:[
           {
               breakpoint:1200,
               settings:{
                slidesToShow:2,
               }
           },
           {
            breakpoint:750,
            settings:{
             slidesToShow:1,
            }  
           }
       ]

    });
});